
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\Ticker\ticker.h"
#include "nlib\StringFormat\stringformat.h"
#include "nlib\StringSerial\stringserial.h"
#include "nlib\KernelPeriod\kernelperiod.h"

// -*-*- List of node objects -*-*-
nBlock_Ticker            nb_nBlockNode0_Ticker       (1000);
nBlock_StringFormat      nb_nBlockNode1_StringFormat ("Value: %d!\n");
nBlock_StringSerial      nb_nBlockNode2_StringSerial (USBTX, USBRX);

nBlock_KernelPeriod     nb_nBlocksNode3_nBlocks_KernelPeriod(0.5);

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode0_Ticker, 0,    &nb_nBlockNode1_StringFormat,    0);
nBlockConnection    n_conn1( &nb_nBlockNode1_StringFormat, 0,    &nb_nBlockNode2_StringSerial,    0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
